using Ship;
using System.Collections.Generic;
using Upgrade;

namespace Editions
{
    public class XWAEdition : SecondEdition
    {
        // Return Second Edition to use same UI panels and pieces without duplicating entire chunks
        //public override string Name { get { return "XWA Edition"; } }
        //public override string NameShort { get { return "XWAEdition"; } }
        public override int MaxPoints { get { return 50; } }

        public XWAEdition() : base() { }

        public override string GetPilotImageUrl(GenericShip ship, string filename)
        {
            return "https://infinitearenas.com/xw2xwa/images/pilots/" + ship.PilotNameCanonical + ".png";
        }

        public override string GetUpgradeImageUrl(GenericUpgrade upgrade, string filename = null)
        {
            return "https://infinitearenas.com/xw2xwa/images/upgrades/" + upgrade.NameCanonical + ".png";
        }

        public override Dictionary<string, string> PreGeneratedAiSquadrons
        {
            get
            {
                Dictionary<string, string> squads = new();

                squads.Add("Chewie Fuel", "{\"name\":\"Chewie Fuel\",\"faction\":\"resistance\",\"ruleset\":\"XWA\",\"points\":50,\"version\":\"50P-2.0\",\"vendor\":{\"Baledin.FlyCasual\":{\"version\":\"v2.5.20260426.02\",\"versionInt\":102508002}},\"pilots\":[{\"id\":\"poedameron-scavengedyt1300\",\"ship\":\"scavengedyt1300\",\"upgrades\":{\"crew\":[\"korrsella\",\"chewbacca-crew-swz19\"],\"gunner\":[\"rey-gunner\"],\"title\":[\"reysmillenniumfalcon\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"colossusstationmechanic\",\"ship\":\"fireball\",\"upgrades\":{\"astromech\":[\"unhingedastromech-legendsandrelics\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"colossusstationmechanic\",\"ship\":\"fireball\",\"upgrades\":{\"astromech\":[\"unhingedastromech-legendsandrelics\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"colossusstationmechanic\",\"ship\":\"fireball\",\"upgrades\":{\"astromech\":[\"unhingedastromech-legendsandrelics\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"colossusstationmechanic\",\"ship\":\"fireball\",\"upgrades\":{\"astromech\":[\"unhingedastromech-legendsandrelics\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"colossusstationmechanic\",\"ship\":\"fireball\",\"upgrades\":{\"astromech\":[\"unhingedastromech-legendsandrelics\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}}],\"obstacles\":[\"coreasteroid5\",\"core2asteroid5\",\"core2asteroid4\"],\"description\":\"Poe Dameron (Scavenged YT-1300) + Korr Sella + Chewbacca + Rey + Rey's Millennium Falcon | Colossus Station Mechanic (Fireball) + Unhinged Astromech | Colossus Station Mechanic (Fireball) + Unhinged Astromech | Colossus Station Mechanic (Fireball) + Unhinged Astromech | Colossus Station Mechanic (Fireball) + Unhinged Astromech | Colossus Station Mechanic (Fireball) + Unhinged Astromech\"}");

                squads.Add("Calc Cloud", "{\"name\":\"Calc Cloud\",\"faction\":\"separatistalliance\",\"ruleset\":\"XWA\",\"points\":50,\"version\":\"50P-2.0\",\"vendor\":{\"Baledin.FlyCasual\":{\"version\":\"v2.5.20260426.02\",\"versionInt\":102508002}},\"pilots\":[{\"id\":\"colicoidinterceptor\",\"ship\":\"droidtrifighter\",\"upgrades\":{\"sensor\":[\"firecontrolsystem\"],\"missile\":[\"discordmissiles\"],\"modification\":[\"independentcalculations\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"colicoidinterceptor\",\"ship\":\"droidtrifighter\",\"upgrades\":{\"sensor\":[\"firecontrolsystem\"],\"missile\":[\"discordmissiles\"],\"modification\":[\"independentcalculations\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"colicoidinterceptor\",\"ship\":\"droidtrifighter\",\"upgrades\":{\"sensor\":[\"firecontrolsystem\"],\"missile\":[\"discordmissiles\"],\"modification\":[\"independentcalculations\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"ig102\",\"ship\":\"rogueclassstarfighter\",\"upgrades\":{\"talent\":[\"marksmanship\"],\"cannon\":[\"syncedlasercannons\"],\"modification\":[\"independentcalculations\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"theironassembler\",\"ship\":\"vultureclassdroidfighter\",\"upgrades\":{\"missile\":[\"energyshellcharges\"],\"modification\":[\"independentcalculations\"],\"configuration\":[\"grapplingstruts\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"dgs286\",\"ship\":\"hmpdroidgunship\",\"upgrades\":{\"missile\":[\"energyshellcharges\",\"clustermissiles\"],\"tactical-relay\":[\"k2b4\"],\"configuration\":[\"repulsorliftstabilizers\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}}],\"obstacles\":[\"coreasteroid5\",\"core2asteroid5\",\"core2asteroid4\"],\"description\":\"Colicoid Interceptor (Droid Tri-Fighter) + Fire-Control System + Discord Missiles + Independent Calculations | Colicoid Interceptor (Droid Tri-Fighter) + Fire-Control System + Discord Missiles + Independent Calculations | Colicoid Interceptor (Droid Tri-Fighter) + Fire-Control System + Discord Missiles + Independent Calculations | IG-102 (Rogue-class Starfighter) + Marksmanship + Synced Laser Cannons + Independent Calculations | The Iron Assembler (Vulture-class Droid Fighter) + Energy-Shell Charges + Independent Calculations + Grappling Struts (Closed) | DGS-286 (HMP Droid Gunship) + Energy-Shell Charges + Cluster Missiles + K2-B4 + Repulsorlift Stabilizers (Inactive)\"}");
                
                // TODO: Add after Tal Merrik added
                //squads.Add("Well Rounded", "{\"description\":\"\",\"faction\":\"separatistalliance\",\"name\":\"Well Rounded\",\"pilots\":[{\"id\":\"sunfac\",\"name\":\"sunfac\",\"points\":13,\"ship\":\"nantexclassstarfighter\",\"upgrades\":{\"talent\":[\"trickshot\",\"predator\",\"lonewolf\"],\"modification\":[\"targetingcomputer\"],\"configuration\":[\"graviticwell-legendsandrelics\"]}},{\"id\":\"magnaguardprotector\",\"name\":\"magnaguardprotector\",\"points\":10,\"ship\":\"rogueclassstarfighter\",\"upgrades\":{\"talent\":[\"deadeyeshot\"],\"cannon\":[\"syncedlasercannons\"],\"modification\":[\"independentcalculations\"]}},{\"id\":\"magnaguardprotector\",\"name\":\"magnaguardprotector\",\"points\":10,\"ship\":\"rogueclassstarfighter\",\"upgrades\":{\"talent\":[\"deadeyeshot\"],\"cannon\":[\"syncedlasercannons\"],\"modification\":[\"independentcalculations\"]}},{\"id\":\"aurrasing\",\"name\":\"aurrasing\",\"points\":17,\"ship\":\"firesprayclasspatrolcraft\",\"upgrades\":{\"force-power\":[\"shatteringshot\"],\"crew\":[\"talmerrik\"],\"title\":[\"slavei-swz82\"]}}],\"points\":50,\"vendor\":{\"yasb\":{\"builder\":\"YASB - X-Wing 2.5 XWA\",\"builder_url\":\"https://yasb.app/\",\"link\":\"https://yasb.app/?f=Separatist%20Alliance&d=v10ZsZ50Z357X133W127W124W249WW625Y542X343W354WW367WY542X343W354WW367WY615X419WWW437WWWW370W&sn=Well%20Rounded&obs=\"}},\"version\":\"50P-2.0\",\"ruleset\":\"XWA\"}");

                squads.Add("No-No Square", "{\"name\":\"No-No Square\",\"faction\":\"rebelalliance\",\"ruleset\":\"XWA\",\"points\":50,\"version\":\"50P-2.0\",\"vendor\":{\"Baledin.FlyCasual\":{\"version\":\"v2.5.20260426.02\",\"versionInt\":102508002}},\"pilots\":[{\"id\":\"chopper-gauntletfighter\",\"ship\":\"gauntletfighter\",\"upgrades\":{\"illicit\":[\"feedbackarray\"],\"modification\":[\"staticdischargevanes\"],\"configuration\":[\"wingedreversal-legendsandrelics\"],\"title\":[\"nightbrother\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"Red\"}}},{\"id\":\"knavesquadronescort\",\"ship\":\"ewing\",\"upgrades\":{\"astromech\":[\"r4astromech\"],\"modification\":[\"retrofittedautothrusters-legendsandrelics\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"knavesquadronescort\",\"ship\":\"ewing\",\"upgrades\":{\"astromech\":[\"r4astromech\"],\"modification\":[\"retrofittedautothrusters-legendsandrelics\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"kullbeesperado\",\"ship\":\"t65xwing\",\"upgrades\":{\"talent\":[\"crackshot\"],\"astromech\":[\"unhingedastromech-legendsandrelics\"],\"modification\":[\"retrofittedautothrusters-legendsandrelics\"],\"configuration\":[\"servomotorsfoils\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"Partisan\"}}}],\"obstacles\":[\"coreasteroid5\",\"core2asteroid5\",\"core2asteroid4\"],\"description\":\"\\\"Chopper\\\" (Gauntlet Fighter) + Feedback Array + Static Discharge Vanes + Winged Reversal + Nightbrother | Knave Squadron Escort (E-wing) + R4 Astromech + Retrofitted Autothrusters | Knave Squadron Escort (E-wing) + R4 Astromech + Retrofitted Autothrusters | Kullbee Sperado (T-65 X-wing) + Crack Shot + Unhinged Astromech + Retrofitted Autothrusters + Servomotor S-Foils (Closed)\"}");

                squads.Add("Focus Luke", "{\"name\":\"Focus Luke\",\"faction\":\"rebelalliance\",\"ruleset\":\"XWA\",\"points\":50,\"version\":\"50P-2.0\",\"vendor\":{\"Baledin.FlyCasual\":{\"version\":\"v2.5.20260426.02\",\"versionInt\":102508002}},\"pilots\":[{\"id\":\"garvendreis\",\"ship\":\"arc170starfighter\",\"upgrades\":{\"talent\":[\"enduring\"],\"astromech\":[\"unhingedastromech-legendsandrelics\"],\"crew\":[\"perceptivecopilot\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"landocalrissian-modifiedyt1300lightfreighter\",\"ship\":\"modifiedyt1300lightfreighter\",\"upgrades\":{\"crew\":[\"perceptivecopilot\",\"jynerso\"],\"modification\":[\"ablativeplating\"],\"title\":[\"millenniumfalcon\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"kylekatarn\",\"ship\":\"hwk290lightfreighter\",\"upgrades\":{\"talent\":[\"hopeful\"],\"crew\":[\"perceptivecopilot\"],\"title\":[\"moldycrow\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"bluesquadronescort\",\"ship\":\"t65xwing\",\"upgrades\":{\"astromech\":[\"unhingedastromech-legendsandrelics\"],\"configuration\":[\"servomotorsfoils\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"Blue\"}}}],\"obstacles\":[\"coreasteroid5\",\"core2asteroid5\",\"core2asteroid4\"],\"description\":\"Garven Dreis (ARC-170 Starfighter) + Enduring + Unhinged Astromech + Perceptive Copilot | Lando Calrissian (Modified YT-1300 Light Freighter) + Perceptive Copilot + Jyn Erso + Ablative Plating + Millennium Falcon | Kyle Katarn (HWK-290 Light Freighter) + Hopeful + Perceptive Copilot + Moldy Crow | Blue Squadron Escort (T-65 X-wing) + Unhinged Astromech + Servomotor S-Foils (Closed)\"}");

                squads.Add("Red Squadron Veterans", "{\"name\":\"Red Squadron Veterans\",\"faction\":\"rebelalliance\",\"ruleset\":\"XWA\",\"points\":50,\"version\":\"50P-2.0\",\"vendor\":{\"Baledin.FlyCasual\":{\"version\":\"v2.5.20260426.02\",\"versionInt\":102508002}},\"pilots\":[{\"id\":\"redsquadronveteran\",\"ship\":\"t65xwing\",\"upgrades\":{\"talent\":[\"predator\"],\"astromech\":[\"r4astromech\"],\"configuration\":[\"servomotorsfoils\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"redsquadronveteran\",\"ship\":\"t65xwing\",\"upgrades\":{\"talent\":[\"predator\"],\"astromech\":[\"r4astromech\"],\"configuration\":[\"servomotorsfoils\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"redsquadronveteran\",\"ship\":\"t65xwing\",\"upgrades\":{\"talent\":[\"predator\"],\"astromech\":[\"r4astromech\"],\"configuration\":[\"servomotorsfoils\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"redsquadronveteran\",\"ship\":\"t65xwing\",\"upgrades\":{\"talent\":[\"predator\"],\"astromech\":[\"r4astromech\"],\"configuration\":[\"servomotorsfoils\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}},{\"id\":\"redsquadronveteran\",\"ship\":\"t65xwing\",\"upgrades\":{\"talent\":[\"predator\"],\"astromech\":[\"r4astromech\"],\"configuration\":[\"servomotorsfoils\"]},\"vendor\":{\"Baledin.FlyCasual\":{\"skin\":\"\"}}}],\"obstacles\":[\"coreasteroid5\",\"core2asteroid5\",\"core2asteroid4\"],\"description\":\"Red Squadron Veteran (T-65 X-wing) + Predator + R4 Astromech + Servomotor S-Foils (Closed) | Red Squadron Veteran (T-65 X-wing) + Predator + R4 Astromech + Servomotor S-Foils (Closed) | Red Squadron Veteran (T-65 X-wing) + Predator + R4 Astromech + Servomotor S-Foils (Closed) | Red Squadron Veteran (T-65 X-wing) + Predator + R4 Astromech + Servomotor S-Foils (Closed) | Red Squadron Veteran (T-65 X-wing) + Predator + R4 Astromech + Servomotor S-Foils (Closed)\"}");

                return squads;
            }
        }
    }
}